# Generated by Django 3.1.1 on 2020-09-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_headline_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headline',
            old_name='price',
            new_name='original_price',
        ),
        migrations.AddField(
            model_name='headline',
            name='promotional_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
