# Generated by Django 3.1.1 on 2020-09-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200915_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='original_price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='promotional_price',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
